name: Bug Report
description: Signaler une anomalie
title: "[Bug]: "
labels: ["bug"]
assignees:
  - vmacp
body:
  - type: markdown
    attributes:
      value: Merci de prendre le temps de renseigner ce formulaire.
  - type: dropdown
    id: environnement
    attributes:
      label: Environnement sur lequel l'anomalie a été constatée
      description: Sur quel environnement l'anomalie a-t-elle été décelée ?
      options:
        - Dev
        - Rec
        - Prod
    validations:
      required: true
  - type: textarea
    id: identification
    attributes:
      label: Nom du traitement en anomalie
      description: Par exemple code flux
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log d'erreur initiale
      description: Merci d'indiquer les log pouvant être utiles.
      render: txt
  - type: textarea
    id: description
    attributes:
      label: Analyse de l'anomalie
      description: Ainsi que description du comportement attendu
      placeholder: Tell us what you see!
      value: "Pensez à inclure des captures d'écran !"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Comment reproduire l'anomalie ?
      description: Étapes pour reproduire l'anomalie sur environnement de développement
      placeholder: Tell us what you see!
      value: "* Étape 1"
    validations:
      required: true
  - type: textarea
    id: cmd
    attributes:
      label: Commande d'exécution du traitement en anomalie
      description: Commande Bash
      render: bash
