name: Bug Report
description: Signaler une anomalie
title: "[Bug]: "
labels: ["bug"]
assignees:
  - vmacp
body:
  - type: markdown
    attributes:
      value: Merci de prendre le temps de renseigner ce formulaire.
  - type: dropdown
    id: environnement
    attributes:
      label: Environnement sur lequel l'anomalie a été constatée
      description: Sur quel environnement l'anomalie a-t-elle été décelée ?
      options:
        - Dev
        - Rec
        - Prod
    validations:
      required: true
  - type: textarea
    id: identification
    attributes:
      label: Référence du traitement en anomalie
      description: Par exemple code flux, ou encore nom d'un job générique
      placeholder: Référence du traitement
    validations:
      required: true
  - type: textarea
    id: incident
    attributes:
      label: Incident / Problème associé
      description: Référence OASIS
      placeholder: INC0000000000
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log d'erreur initiale
      description: Par exemple log Automator
      render: txt
  - type: textarea
    id: analyse
    attributes:
      label: Analyse de l'anomalie
      description: Description du comportement observé VS comportement attendu
      placeholder: Pensez à inclure des captures d'écran !
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Comment reproduire l'anomalie ?
      description: Liste des actions permettant de reproduire le bug
      placeholder: Étapes pour reproduire l'anomalie
    validations:
      required: true
  - type: textarea
    id: cmd
    attributes:
      label: Commande d'exécution du traitement en anomalie
      description: Commande Bash
      render: bash
