name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - vmacp
body:
  - type: markdown
    attributes:
      value: Merci de prendre le temps de renseigner ce formulaire.
  - type: textarea
    id: what-happened
    attributes:
      label: Description de l'anomalie
      description: Ainsi que description du comportement attendu
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Environnement
    attributes:
      label: Environnement
      description: Sur quel environnement l'anomalie a-t-elle été décelée ?
      options:
        - dev
        - rec
        - prod
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log
      description: Merci d'indiquer les log pouvant être utiles.
      render: shell
