name: Bug Report
description: File a bug report
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - vmacp
body:
  - type: markdown
    attributes:
      value: Merci de prendre le temps de renseigner ce formulaire.
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: En quoi le projet peut être amélioré
      placeholder: Tell us what you see!
      value: "Description"
    validations:
      required: true
