name: Feature Request
description: Proposer une amélioration ou un nouveau besoin
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - vmacp
body:
  - type: markdown
    attributes:
      value: Merci de prendre le temps de renseigner ce formulaire.
  - type: dropdown
    id: type
    attributes:
      label: Type de traitement concerné
      description: Traitement à faire évoluer
      options:
        - TIG
        - TPG
        - TEG Fichier
        - TEG Oracle
        - TEG Postgres
        - TEG GCS
        - TEG BQ
        - Ingest spécifique Talend
        - Produce spécifique Dataiku
        - Autre
    validations:
      required: true
  - type: textarea
    id: traitement
    attributes:
      label: Référence du traitement
      description: Par exemple code flux, ou encore nom d'un job générique
      placeholder: Référence du traitement
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: En quoi le traitement peut être amélioré
      placeholder: Description de l'amélioration
    validations:
      required: true
  - type: textarea
    id: step
    attributes:
      label: Mise en œuvre
      description: Étapes de mise en œuvre de l'amélioration
      placeholder: À faire
    validations:
      required: false
